steps:
- name: 'docker.io/library/python:3.7'
  args: ['bash', 'test.sh']
  dir: 'bin'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'cloud-build-test-function', '--runtime', '--trigger-http', '--entry-point=main', '--runtime=python37', '--source=src']
