steps:
- name: 'gcr.io/google-appengine/python'
  args: ['bash', 'test.sh']
  dir: 'bin'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'cloud-build-test-function', '--runtime', '--trigger-http', '--entry-point=main', '--runtime=python37']
  dir: 'src'
